version: '3'

services: 
    web:
        image: nginx
        restart: always
        volumes: 
            - ./src:/app
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
        depends_on:
            - php-fpm
        ports:
            - 80:80
    php-fpm:
        image: php:8.1.19-fpm-bullseye
        restart: always
        volumes:
            - ./src:/app
